services:
    heartbeat:
      build:
        context: ../.
        dockerfile: ./build/package/heartbeat/Dockerfile
      ports:
        - 1234:1234
      environment:
        - HOSTNAME="localhost"
        - PORT=:1234
    
      