name: Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          # Install Yarn
          yarn: true

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run
        env:
          ACTION_TYPE: publish
          branch: ${{ github.head_ref }}
        run: node main.js
