name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  your_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Running script
        run: python main.py
      - name: Use flag in a step
        run: |
          # Read the flag value from the file
          flag=$(cat flag.txt)
          echo "Flag value is $flag"
